packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": 26.6.4
  better-auth: 1.7.7
  typescript: "7.0.2"
  vite: 8.3.2
  vitest: 5.0.3

peerDependencyRules:
  allowedVersions:
    "better-auth@1.7.7>solid-js": "2.0.0-rc.13"
    "surrealdb@2.0.10>typescript": "7.0.2"
    "@surrealdb/sqon@0.1.5>typescript": "7.0.2"

allowBuilds:
  esbuild: true
  msgpackr-extract: true
